/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.doublerebel.titestflight;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import com.testflightapp.lib.TestFlight;


@Kroll.module(name="TiTestflight", id="com.doublerebel.titestflight")
public class TiTestflightModule extends KrollModule
{

    // Standard Debugging variables
    private static final String TAG = "TiTestflightModule";

    // You can define constants with @Kroll.constant, for example:
    // @Kroll.constant public static final String EXTERNAL_NAME = value;

    public TiTestflightModule()
    {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app)
    {
        Log.d(TAG, "inside onAppCreate");
        // put module init code that needs to run when the application is created
    }

    // Methods
    @Kroll.method
    public void takeOff(String token)
    {
        Log.d(TAG, "takeOff called with token: " + token);
        TiApplication appContext = TiApplication.getInstance();
        TestFlight.takeOff(appContext, token);
    }

    @Kroll.method
    public void land()
    {
        Log.d(TAG, "landing...");
        TestFlight.land();
    }

    @Kroll.method
    public void passCheckpoint(String checkpointName)
    {
        Log.d(TAG, "passCheckpoint called for checkpoint: " + checkpointName);
        TestFlight.passCheckpoint(checkpointName);
    }

    @Kroll.method
    public void log(String msg)
    {
        Log.d(TAG, "log called with message: " + msg);
        TestFlight.log(msg);
    }

    // Properties
    // @Kroll.getProperty
    // public String getExampleProp()
    // {
    //     Log.d(TAG, "get example property");
    //     return "hello world";
    // }


    // @Kroll.setProperty
    // public void setExampleProp(String value) {
    //     Log.d(TAG, "set example property: " + value);
    // }

}

